apiVersion: v1
kind: Secret
metadata:
  name: connection-string-secret
type: Opaque
stringData:
  DataContext: User ID=application;Password=password;Server=postgresql;Port=5432;Database=HomeTask4;
  DataContextMigrations: User ID=postgres;Password=postgres;Server=postgresql;Port=5432;Database=HomeTask4;